theme: jekyll-theme-minimal
title: Pierre Pora
description: Economist at <a href="{{ https://insee.fr/fr/accueil }}">Insee</a>, <a href="{{ http://crest.science/ }}">Crest</a> affiliate, Ph.D. student at <a href="{{ https://economix.fr/ }}">EconomiX</a>
show_downloads: false
