theme: jekyll-theme-minimal
title: Pierre Pora
description: Statisticien-économiste à l'<a href="https://insee.fr">Insee</a>, chercheur affilié au <a href="http://crest.science/">Crest</a></a>
contact: "pierre.pora[at]ensae.fr"
show_downloads: false
