theme: jekyll-theme-minimal
title: Pierre Pora
description: Economist at <a href="https://drees.solidarites-sante.gouv.fr/etudes-et-statistiques/">Drees</a>, <a href="http://crest.science/">Crest</a> affiliate, Ph.D. student at <a href="https://economix.fr/">EconomiX</a>
contact: "pierre.pora[at]ensae.fr"
show_downloads: false
